version: "3.9"

services:
    postgres:
        env_file:
            - ".env"
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgres/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
